/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ReportesVentanas;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author janus
 */
public class JIFClienteMasCompras extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFClienteMasCompras
     */
   
    public JIFClienteMasCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientess = new javax.swing.JPanel();
        jDatefechaInicio = new com.toedter.calendar.JDateChooser();
        jDatefechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        clientess.setBackground(new java.awt.Color(255, 102, 51));
        clientess.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        clientess.add(jDatefechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, -1));
        clientess.add(jDatefechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FECHA FINAL");
        clientess.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FECHA INICIO");
        clientess.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, -1));

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCliente);

        clientess.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 840, 390));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        clientess.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientess, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       Conexion con = new Conexion();
        if (jDatefechaFinal.getDate() == null || jDatefechaInicio.getDate() == null ) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona una fecha de inicio y final", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Date fechaInicio = new Date(jDatefechaInicio.getDate().getTime());
        Date fechaFinal = new Date(jDatefechaFinal.getDate().getTime());

        try (Connection connection = DriverManager.getConnection(con.getUrl(), con.getUser(), con.getPass())) {
            PreparedStatement stmt = connection.prepareCall("call clienteMasCompra(?,?)");
            stmt.setDate(1, fechaInicio);
            stmt.setDate(2, fechaFinal);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("CLIENTE ");
            modelo.addColumn("Total Compras");
            while (rs.next()) {
                Object[] fila = new Object[2];
                fila[0] = rs.getString("Cliente");
                fila[1] = rs.getInt("TotalCompras");
               
                modelo.addRow(fila);
            }
            tableCliente.setModel(modelo);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
       
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel clientess;
    private com.toedter.calendar.JDateChooser jDatefechaFinal;
    private com.toedter.calendar.JDateChooser jDatefechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCliente;
    // End of variables declaration//GEN-END:variables
}
