/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ReportesVentanas;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author janus
 */
public class JIFReporteVentasRealizadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReporteVentasRealizadas
     */
    
    public JIFReporteVentasRealizadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDatefechaFinal = new com.toedter.calendar.JDateChooser();
        jDatefechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        lbfecha2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lbFecha1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("VENTAS REALIZADAS");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDatefechaFinal.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(jDatefechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 150, -1));

        jDatefechaInicio.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(jDatefechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 140, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        lbfecha2.setForeground(new java.awt.Color(0, 0, 0));
        lbfecha2.setText("Fecha Final");
        jPanel1.add(lbfecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 130, 40));

        lbFecha1.setForeground(new java.awt.Color(0, 0, 0));
        lbFecha1.setText("Fecha Inicio");
        jPanel1.add(lbFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1020, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
          Conexion con = new Conexion();
        if (jDatefechaFinal.getDate() == null || jDatefechaInicio.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona una fecha de inicio y final.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Date fechaInicio = new Date(jDatefechaInicio.getDate().getTime());
            Date fechaFinal = new Date(jDatefechaFinal.getDate().getTime());
            try (Connection connection = DriverManager.getConnection(con.getUrl(), con.getUser(), con.getPass())) {
                PreparedStatement stmt = connection.prepareCall("call obtenerVentasPorFecha(?,?)");
                stmt.setDate(1, fechaInicio);
                stmt.setDate(2, fechaFinal);

                ResultSet rs = stmt.executeQuery();
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.addColumn(" EMPLEADO");
                modelo.addColumn(" PRODUCTO");
                modelo.addColumn("CANTIDAD VENDIDA");
                modelo.addColumn("NOMBRE CLIENTE ");
                modelo.addColumn("CEDULA CLIENTE");
                modelo.addColumn("FECHA ");
                modelo.addColumn("TOTAL");
                while (rs.next()) {
                    Object[] fila = new Object[7];
                    fila[0] = rs.getString("nombreEmpleado");
                    fila[1] = rs.getString("nombreProducto");
                    fila[2] = rs.getInt("cantidadVendida");
                    fila[3] = rs.getString("nombreCliente");
                    fila[4] = rs.getString("nitCliente");
                    fila[5] = rs.getDate("fechaVenta");
                    fila[6] = rs.getDouble("totalpagar");

                    modelo.addRow(fila);
                }
                tablaVentas.setModel(modelo);
            } catch (SQLException e) {
                e.printStackTrace();
                System.out.println(e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed
 
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private com.toedter.calendar.JDateChooser jDatefechaFinal;
    private com.toedter.calendar.JDateChooser jDatefechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFecha1;
    private javax.swing.JLabel lbfecha2;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
