/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ReportesVentanas;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author janus
 */
public class JIFVendedorFechas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFVendedorFechas
     */
    public JIFVendedorFechas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDatefechaInicio = new com.toedter.calendar.JDateChooser();
        jDatefechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReportes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vendedor Por Fechas");

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha Inicio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha Final");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jDatefechaInicio.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(jDatefechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 180, -1));

        jDatefechaFinal.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(jDatefechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 160, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Empleado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 120, -1));
        jPanel1.add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 140, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 150, 40));

        tableReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableReportes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 890, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
      Conexion con = new Conexion();
        if (jDatefechaFinal.getDate() == null || jDatefechaInicio.getDate() == null || txtEmpleado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona una fecha de inicio y final y el nombre del empleado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Date fechaInicio = new Date(jDatefechaInicio.getDate().getTime());
        Date fechaFinal = new Date(jDatefechaFinal.getDate().getTime());

        try (Connection connection = DriverManager.getConnection(con.getUrl(), con.getUser(), con.getPass())) {
            PreparedStatement stmt = connection.prepareCall("call ventasEmpleado(?,?,?)");
            stmt.setString(1, txtEmpleado.getText());
            stmt.setDate(2, fechaInicio);
            stmt.setDate(3, fechaFinal);

            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Vendedor");
            modelo.addColumn("Ventas");
            modelo.addColumn("Producto");
            modelo.addColumn("Precio");
            modelo.addColumn("Total Cantidad Vendida");
            modelo.addColumn("Total Recaudado");
            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getString("Vendedor");
                fila[1] = rs.getInt("Ventas");
                fila[2] = rs.getString("Producto");
                fila[3] = rs.getDouble("Precio");
                fila[4] = rs.getInt("TotalCantidadVendida");
                fila[5] = rs.getDouble("TotalRecaudado");
                modelo.addRow(fila);
            }
            tableReportes.setModel(modelo);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
       
        
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private com.toedter.calendar.JDateChooser jDatefechaFinal;
    private com.toedter.calendar.JDateChooser jDatefechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReportes;
    private javax.swing.JTextField txtEmpleado;
    // End of variables declaration//GEN-END:variables
}
