
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author janus
 */
public class Activarproducto extends javax.swing.JFrame {

    /**
     * Creates new form Activarproducto
     */
    private int idProducto;
    String usuarios;
    int empleados, id;
    public Activarproducto(String usar, int emplea, int ides) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarios=usar;
        this.empleados=emplea;
        this.id=ides;
        mostrarDatos();
    }

    private Activarproducto() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnActi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableActivar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnActivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoFerreteria.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 159, -1));

        btnActi.setBackground(new java.awt.Color(0, 255, 102));
        btnActi.setForeground(new java.awt.Color(0, 0, 0));
        btnActi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Devolver.png"))); // NOI18N
        btnActi.setText("DEVOLVER");
        btnActi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiActionPerformed(evt);
            }
        });
        jPanel1.add(btnActi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, 40));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableActivar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableActivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableActivarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableActivar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DIGITE EL NOMBRE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 30));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 210, 40));

        btnActivar.setBackground(new java.awt.Color(102, 204, 255));
        btnActivar.setForeground(new java.awt.Color(0, 0, 0));
        btnActivar.setText("ACTIVAR");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        if(txtNombre.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "ingresa el nombre del producto Activar", "elije un producto", JOptionPane.ERROR_MESSAGE);
        return;
    }
        Conexiones con = new Conexiones();
        try (Connection conexion = DriverManager.getConnection(con.url, con.user, con.pass)) {
            try (PreparedStatement stmtConsulta = conexion.prepareCall("call obteneridProducto(?)")) {
              String  nombre = txtNombre.getText();
                stmtConsulta.setString(1, nombre);
                try (ResultSet rs = stmtConsulta.executeQuery()) {
                    if (rs.next()) {
                        idProducto = rs.getInt("id_producto");
                        String procedimiento = "{call activarProducto(?)}";
                        try (PreparedStatement stmtDesactivar = conexion.prepareCall(procedimiento)) {
                            stmtDesactivar.setInt(1, idProducto);
                            stmtDesactivar.executeUpdate();
                           JOptionPane.showMessageDialog(rootPane, "producto activado correctamente "  +  nombre);
                            mostrarDatos();
                        }
                    } else {
                       JOptionPane.showMessageDialog(rootPane, "no se encontro ningun producto");
                    }
                }
            }
        } catch (SQLException e) {
            System.out.println("Error al desactivar el producto: " + e.getMessage());
}
    
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnActiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiActionPerformed
            Añadir aña = new Añadir(empleados, usuarios, id);
            aña.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnActiActionPerformed

    private void tableActivarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableActivarMouseClicked
  int seleccionar = tableActivar.rowAtPoint(evt.getPoint());
        txtNombre.setText(String.valueOf(tableActivar.getValueAt(seleccionar, 0)));
    }//GEN-LAST:event_tableActivarMouseClicked
public void mostrarDatos() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            tableActivar.setModel(model);
            Conexiones con = new Conexiones();
            try (Connection connection = DriverManager.getConnection(con.getUrl(), con.getUser(), con.getPass())) {

                try (PreparedStatement stmt = connection.prepareCall("call mostrarProductosInactivos()")) {
                    ResultSet ps = stmt.executeQuery();
                    ResultSetMetaData metaData = ps.getMetaData();

                    for (int i = 1; i <= metaData.getColumnCount(); i++) {
                        model.addColumn(metaData.getColumnLabel(i));
                    }
                    while (ps.next()) {
                        Object[] filas = new Object[metaData.getColumnCount()];
                        for (int i = 0; i < metaData.getColumnCount(); i++) {
                            filas[i] = ps.getObject(i + 1);
                        }
                        model.addRow(filas);
                    }
                    ps.close();
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error de base de datos: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activarproducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActi;
    private javax.swing.JButton btnActivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableActivar;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
